// MoonUp Neural SR v2 runtime (weights in neural_weights.h, generated by tools/train_neural.py).
// Runs either the MoonUp model (realistic games) or ArtCNN C4F16 (anime / 2D, MIT).
#pragma once
#include "d3d.h"

namespace sw {

class NeuralUpscaler {
public:
    enum Model { kMoonUp = 0, kArtCNN = 1 };
    bool Init(Gpu& gpu, ShaderLibrary& lib);
    bool Ready() const { return ready_; }
    // Upscales 'src' to out.width x out.height (out must be larger than src).
    bool Run(ID3D11ShaderResourceView* src, UINT srcW, UINT srcH, Texture& out, Model model = kMoonUp);
    const std::string& Error() const { return error_; }

private:
    static constexpr int kLayers = 7;
    Gpu* gpu_ = nullptr;
    ShaderLibrary* lib_ = nullptr;
    ConstantBuffer cb_, cbUp_;
    ComPtr<ID3D11Buffer> layerCb_[2][kLayers];
    Texture s_[4], a_[4], b_[4], out2x_;
    bool ready_ = false;
    std::string error_;
};

}  // namespace sw
