# Embeds the DXBC blobs compiled at build time (tools/build_shaders.sh -> build/shader_bin) into
# src/engine/shaders_bin.h. Without blobs it writes an empty table (shaders compile at runtime).
import os, sys
root = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..')
bindir = os.path.join(root, 'build', 'shader_bin')
out = os.path.join(root, 'src', 'engine', 'shaders_bin.h')
entries = []
idx = os.path.join(bindir, 'index.txt')
if os.path.exists(idx) and '--empty' not in sys.argv:
    for line in open(idx):
        p = line.split()
        if len(p) >= 3:
            entries.append((p[0], p[1], open(os.path.join(bindir, p[2]), 'rb').read()))
with open(out, 'w', newline='\n') as f:
    f.write('// AUTO-GENERATED by tools/embed_shader_blobs.py - precompiled shaders (DXBC, d3dcompiler_47).\n')
    f.write('#pragma once\n#include <cstdio>\n#include <cstring>\nnamespace sw { namespace shaders_bin {\n')
    f.write('struct Blob { const char* key; unsigned long long hash; const unsigned char* data; unsigned size; };\n')
    for i, (k, h, b) in enumerate(entries):
        f.write('static const unsigned char kB%d[%d] = {%s};\n' % (i, len(b), ','.join(str(x) for x in b)))
    f.write('static const Blob kBlobs[] = {\n')
    for i, (k, h, b) in enumerate(entries):
        f.write('  {"%s", 0x%sull, kB%d, %du},\n' % (k, h, i, len(b)))
    if not entries:
        f.write('  {"", 0ull, nullptr, 0u},\n')
    f.write('};\n')
    f.write('inline const Blob* Find(const char* file, const char* entry, const char* profile, unsigned long long hash) {\n')
    f.write('    char key[160];\n    snprintf(key, sizeof(key), "%s:%s:%s", file, entry, profile);\n')
    f.write('    for (auto& b : kBlobs)\n        if (b.data && b.hash == hash && !strcmp(b.key, key)) return &b;\n    return nullptr;\n}\n}}\n')
print('embedded %d shader blobs (%d KB)' % (len(entries), sum(len(b) for _, _, b in entries) // 1024))
