# Embeds src/engine/shaders/*.hlsl(i) into a generated C++ header as raw string literals.
import os, sys, glob
root = os.path.join(os.path.dirname(__file__), '..', 'src', 'engine', 'shaders')
out = os.path.join(os.path.dirname(__file__), '..', 'src', 'engine', 'shaders_gen.h')
files = sorted(glob.glob(os.path.join(root, '*.hlsl*')))
with open(out, 'w', newline='\n') as f:
    f.write('// AUTO-GENERATED by tools/embed_shaders.py - do not edit.\n#pragma once\n#include <cstring>\nnamespace sw { namespace shaders {\n')
    f.write('struct Source { const char* name; const char* text; };\n')
    f.write('static const Source kSources[] = {\n')
    for p in files:
        name = os.path.basename(p)
        text = open(p).read()
        # split long literals to stay under compiler limits
        chunks = [text[i:i+12000] for i in range(0, len(text), 12000)]
        f.write('  {"%s",\n' % name)
        for c in chunks:
            f.write('R"SWHLSL(%s)SWHLSL"\n' % c)
        f.write('  },\n')
    f.write('};\n')
    f.write('inline const char* Find(const char* name) { for (auto& s : kSources) if (!strcmp(s.name, name)) return s.text; return nullptr; }\n')
    f.write('}}\n')
print('embedded', len(files), 'shader files')
