#!/usr/bin/env python3
"""Generates the MoonUp Upgraph ReShade effect from the Neural Render v3 weights.

Outputs
  build/upgraph/MoonUpUpgraph.fx              ReShade FX effect
  build/upgraph/moonup_upgraph_weights.png    tone network weights, float32 bits in RGBA8
  src/upgraph/upgraph_assets.h                  both files embedded in MoonUp.exe
"""
import os, re, struct, zlib

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
HDR = os.path.join(ROOT, "src/engine/render_weights.h")
TEMPLATE = os.path.join(ROOT, "tools/upgraph/MoonUpUpgraph.fx.in")
OUT_DIR = os.path.join(ROOT, "build/upgraph")
ASSETS = os.path.join(ROOT, "src/upgraph/upgraph_assets.h")
WIDTH = 512


def load_weights():
    text = open(HDR).read()
    offs = {m.group(1): int(m.group(2)) for m in re.finditer(r"kOff_(\w+) = (\d+);", text)}
    count = int(re.search(r"kWeightCount = (\d+);", text).group(1))
    body = text[text.index("kWeights[") :]
    body = body[body.index("{") + 1 : body.index("}")]
    vals = [float(v.rstrip("f")) for v in body.replace("\n", "").split(",") if v.strip()]
    assert len(vals) == count, (len(vals), count)
    return offs, vals


def png_rgba(width, height, raw_rows):
    def chunk(tag, data):
        c = struct.pack(">I", len(data)) + tag + data
        return c + struct.pack(">I", zlib.crc32(tag + data) & 0xFFFFFFFF)

    ihdr = struct.pack(">IIBBBBB", width, height, 8, 6, 0, 0, 0)
    data = b"".join(b"\x00" + r for r in raw_rows)
    return b"\x89PNG\r\n\x1a\n" + chunk(b"IHDR", ihdr) + chunk(b"IDAT", zlib.compress(data, 9)) + chunk(b"IEND", b"")


def fmt(v):
    s = "%.9g" % v
    if "e" not in s and "." not in s:
        s += ".0"
    return s


def array(name, vals):
    lines = []
    for i in range(0, len(vals), 8):
        lines.append("    " + ", ".join(fmt(v) for v in vals[i : i + 8]))
    return "static const float %s[%d] = {\n%s\n};" % (name, len(vals), ",\n".join(lines))


def main():
    offs, w = load_weights()
    n = len(w)
    height = (n + WIDTH - 1) // WIDTH
    raw = struct.pack("<%df" % n, *w) + b"\x00" * 4 * (WIDTH * height - n)
    rows = [raw[y * WIDTH * 4 : (y + 1) * WIDTH * 4] for y in range(height)]
    png = png_rgba(WIDTH, height, rows)

    tone = ["c1w", "c1b", "c2w", "c2b", "c3w", "c3b", "c4w", "c4b", "c5w", "c5b", "c6w", "c6b", "f1w", "f1b", "f2w", "f2b", "ow", "ob"]
    offsets = "\n".join("static const int UG_%s = %d;" % (k, offs[k]) for k in tone)

    layers = []
    sizes = [120, 1308, 1308, 1308, 1308, 218]
    for i in range(6):
        start = offs["s%dw" % (i + 1)]
        vals = w[start : start + sizes[i]]
        assert offs["s%db" % (i + 1)] - start == sizes[i] - (12 if i < 5 else 2)
        layers.append(array("UG_S%d" % (i + 1), vals))
    guide = array("UG_G", w[offs["ccm"] : offs["ccm"] + 64])

    fx = open(TEMPLATE).read()
    fx = fx.replace("/*@@WH@@*/", str(height))
    fx = fx.replace("/*@@OFFSETS@@*/", offsets)
    fx = fx.replace("/*@@STRUCT_WEIGHTS@@*/", "\n".join(layers))
    fx = fx.replace("/*@@GUIDE@@*/", guide)
    assert "@@" not in fx

    os.makedirs(OUT_DIR, exist_ok=True)
    open(os.path.join(OUT_DIR, "MoonUpUpgraph.fx"), "w", newline="\n").write(fx)
    open(os.path.join(OUT_DIR, "moonup_upgraph_weights.png"), "wb").write(png)

    def c_bytes(name, data):
        out = ["static const unsigned char %s[%d] = {" % (name, len(data))]
        for i in range(0, len(data), 32):
            out.append(",".join(str(b) for b in data[i : i + 32]) + ",")
        out.append("};")
        return "\n".join(out)

    os.makedirs(os.path.dirname(ASSETS), exist_ok=True)
    with open(ASSETS, "w") as f:
        f.write("// AUTO-GENERATED by tools/gen_upgraph.py - MoonUp Upgraph ReShade effect and weights.\n#pragma once\n")
        f.write("namespace sw { namespace upgraph_assets {\n")
        f.write(c_bytes("kFx", fx.encode("utf-8")) + "\n")
        f.write(c_bytes("kWeightsPng", png) + "\n")
        f.write("}}\n")
    print("fx %d bytes, png %d bytes (%dx%d)" % (len(fx), len(png), WIDTH, height))


if __name__ == "__main__":
    main()
