# Generates a C++ COM header for WebView2 from webview2-com-sys bindings.rs
# (vtable order + IIDs are taken verbatim from the generated Rust bindings).
import re, sys
src = ''.join(open(p).read() for p in sys.argv[1].split(','))
out = open(sys.argv[2], 'w')

iids = {}
for m in re.finditer(r'define_interface!\(\s*(\w+),\s*(\w+),\s*0x([0-9a-f_]+)\s*\)', src):
    iids[m.group(1)] = m.group(3).replace('_', '')

structs = {}
for m in re.finditer(r'pub struct (\w+)_Vtbl \{', src):
    name = m.group(1)
    i = m.end(); depth = 1
    while depth:
        c = src[i]
        if c == '{': depth += 1
        elif c == '}': depth -= 1
        i += 1
    body = src[m.end():i-1]
    structs[name] = body

def map_type(t):
    t = re.sub(r'\b\w+::', '', t.strip()); t = t.replace('windows_core::', '').replace('core::ffi::', '').replace('windows::Win32::Foundation::', '').replace('windows::Win32::UI::WindowsAndMessaging::','').replace('windows::Win32::Graphics::Gdi::','')
    t = re.sub(r'\s+', ' ', t)
    ptr = 0
    while t.startswith('*mut ') or t.startswith('*const '):
        t = t.split(' ', 1)[1]; ptr += 1
    base = {
        'c_void': 'void', 'PCWSTR': 'LPCWSTR', 'PWSTR': 'LPWSTR', 'BOOL': 'BOOL', 'HRESULT': 'HRESULT',
        'i64': 'INT64', 'u64': 'UINT64', 'i32': 'INT32', 'u32': 'UINT32', 'i16': 'INT16', 'u16': 'UINT16',
        'u8': 'BYTE', 'i8': 'char', 'f64': 'double', 'f32': 'float', 'RECT': 'RECT', 'POINT': 'POINT',
        'HWND': 'HWND', 'HCURSOR': 'HCURSOR', 'HANDLE': 'HANDLE', 'GUID': 'GUID', 'usize': 'size_t',
        'COREWEBVIEW2_COLOR': 'COREWEBVIEW2_COLOR', 'SizeInt32': 'WgcSizeInt32', 'TimeSpan': 'INT64', 'bool': 'BYTE', 'DirectXPixelFormat': 'INT32', 'GraphicsCaptureAccessKind':'INT32', 'DirectXAlphaMode':'INT32', 'HSTRING':'HSTRING', 'Win32::Graphics::Gdi::HMONITOR':'HMONITOR', 'COREWEBVIEW2_PHYSICAL_KEY_STATUS': 'COREWEBVIEW2_PHYSICAL_KEY_STATUS',
        'EventRegistrationToken': 'INT64', 'VARIANT': 'VARIANT', 'Variant::VARIANT': 'VARIANT',
        'windows::Win32::System::Variant::VARIANT': 'VARIANT', 'Option < IUnknown >': 'IUnknown*',
    }
    if t in base: b = base[t]
    elif re.fullmatch(r'COREWEBVIEW2_\w+', t): b = 'INT32'   # enums are i32 newtypes
    elif re.fullmatch(r'I\w+', t): b = 'void'; ptr += 1   # interface by value == pointer
    else:
        b = 'void* /*%s*/' % t
    return b + '*' * ptr

names_out = []
def emit(name, seen):
    if name in seen or name not in structs: return
    body = structs[name]
    bm = re.search(r'pub base__:\s*([\w:]+)_Vtbl', body)
    base = bm.group(1).split('::')[-1] if bm else 'IUnknown'
    if base not in ('IUnknown','IInspectable'): emit(base, seen)
    seen.add(name)
    fields = []
    for fm in re.finditer(r'pub (\w+):\s*(unsafe extern "system" fn\(|usize)', body):
        fname = fm.group(1)
        if fname == 'base__': continue
        if fm.group(2) == 'usize':
            fields.append((fname, None, None)); continue
        j = fm.end(); depth = 1
        while depth:
            c = body[j]
            if c == '(': depth += 1
            elif c == ')': depth -= 1
            j += 1
        args = body[fm.end():j-1]
        rest = body[j:j+60]
        ret = 'HRESULT'
        rm = re.match(r'\s*->\s*([\w:]+)', rest)
        if rm: ret = map_type(rm.group(1))
        parts = [a.strip() for a in re.split(r',(?![^<]*>)', args) if a.strip()]
        parts = parts[1:]  # drop this
        fields.append((fname, [map_type(p) for p in parts], ret))
    iid = iids.get(name)
    out.write('struct %s : public %s {\n' % (name, base))
    for idx, (fname, args, ret) in enumerate(fields):
        if args is None:
            out.write('  virtual void STDMETHODCALLTYPE _unsupported_%s() = 0;\n' % fname); continue
        al = ', '.join('%s a%d' % (a, k) for k, a in enumerate(args))
        out.write('  virtual %s STDMETHODCALLTYPE %s(%s) = 0;\n' % (ret, fname, al))
    out.write('};\n')
    if iid:
        g = iid.rjust(32, '0')
        out.write('static const GUID IID_%s = {0x%s,0x%s,0x%s,{0x%s,0x%s,0x%s,0x%s,0x%s,0x%s,0x%s,0x%s}};\n\n' % (
            name, g[0:8], g[8:12], g[12:16], g[16:18], g[18:20], g[20:22], g[22:24], g[24:26], g[26:28], g[28:30], g[30:32]))

out.write('''// AUTO-GENERATED by tools/gen_com_header.py from Rust windows-bindgen metadata.
// COM/WinRT ABI interface subset (vtable order + IIDs from official metadata). Do not edit by hand.
#pragma once
#include <windows.h>
#include <oaidl.h>
struct COREWEBVIEW2_COLOR { BYTE A, R, G, B; };
struct WgcSizeInt32 { INT32 Width; INT32 Height; };
struct COREWEBVIEW2_PHYSICAL_KEY_STATUS { UINT32 RepeatCount; UINT32 ScanCode; BOOL IsExtendedKey; BOOL IsMenuKeyDown; BOOL WasKeyDown; BOOL IsKeyReleased; };
''')
want = sys.argv[3].split(',')
mode = sys.argv[4] if len(sys.argv)>4 else 'wv2'
seen = set()
for w in want: emit(w, seen)
if mode=='wv2': out.write('extern "C" typedef HRESULT (STDAPICALLTYPE *PFN_CreateCoreWebView2EnvironmentWithOptions)(LPCWSTR, LPCWSTR, void*, ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandler*);\n')
out.close()
